{% set name = "firefly-client" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: ad5a6efb0231b0b25ed5797789005bd2802a89e74fc0d9778febe58d5584915c

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - requests
    - setuptools
    - websocket-client

test:
  requires:
    - python {{ python_min }}
  imports:
    - firefly_client

about:
  home: http://github.com/Caltech-IPAC/firefly_client
  # license file manually packaged. See: https://github.com/Caltech-IPAC/firefly_client/pull/42
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  summary: Python API for Firefly, IPAC's Advanced Astronomy Web UI Framework
  description: |
    Firefly client is a python client to be used against the Firefly web
    UI framework and visualization system for astronomical archives.
  dev_url: https://github.com/Caltech-IPAC/firefly_client

extra:
  recipe-maintainers:
    - brianv0
    - robyww
    - loitly
    - jaladh-singhal
