{% set name = "firefly-client" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 179cb72230787e9d4248f87bfa627f40ef09abfd308626ba3f213d163827c551

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - future
    - requests
    - setuptools
    - ws4py

test:
  imports:
    - firefly_client

about:
  home: http://github.com/Caltech-IPAC/firefly_client
  # license file manually packaged. See: https://github.com/Caltech-IPAC/firefly_client/pull/42
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  summary: Python API for Firefly, IPAC's Advanced Astronomy Web UI Framework
  description: |
    Firefly client is a python client to be used against the Firefly web
    UI framework and visualization system for astronomical archives.
  dev_url: https://github.com/Caltech-IPAC/firefly_client

extra:
  recipe-maintainers:
    - brianv0
    - robyww
    - loitly
